# Generated by Django 4.0.1 on 2022-01-16 07:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UUID', models.UUIDField(default=uuid.UUID('2dae16bb-700c-4ee2-8077-5c897aa6c0fe'), primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('daysBeforeExpire', models.IntegerField()),
                ('UUID', models.ForeignKey(default=uuid.UUID('ae40f3f2-15e8-482c-b6de-bd77fdc8ab62'), on_delete=django.db.models.deletion.CASCADE, to='recipe_app.user')),
            ],
            options={
                'unique_together': {('name', 'UUID')},
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=200)),
                ('UUID', models.ForeignKey(default=uuid.UUID('0d111607-1d50-4cad-86e5-3f474935ee7c'), on_delete=django.db.models.deletion.CASCADE, to='recipe_app.user')),
            ],
            options={
                'unique_together': {('id', 'UUID')},
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('datePurchased', models.DateField()),
                ('daysBeforeExpire', models.IntegerField()),
                ('UUID', models.ForeignKey(default=uuid.UUID('b851e560-8ed0-4466-a11d-ccfa1002f031'), on_delete=django.db.models.deletion.CASCADE, to='recipe_app.user')),
            ],
            options={
                'unique_together': {('UUID', 'name', 'datePurchased')},
            },
        ),
    ]
