# Generated by Django 4.0.1 on 2022-01-16 17:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_user_alter_food_unique_together_food_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='datePurchased',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='UUID',
            field=models.ForeignKey(default=uuid.UUID('b1e4ed5e-8d83-4e6a-bbfb-aceeb5faaa6c'), on_delete=django.db.models.deletion.CASCADE, to='recipe_app.user'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='UUID',
            field=models.ForeignKey(default=uuid.UUID('723e8689-4fa1-483c-adef-3b3734e02ccd'), on_delete=django.db.models.deletion.CASCADE, to='recipe_app.user'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='UUID',
            field=models.ForeignKey(default=uuid.UUID('74cc7966-8185-44ca-914f-436d2ad4350e'), on_delete=django.db.models.deletion.CASCADE, to='recipe_app.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UUID',
            field=models.UUIDField(default=uuid.UUID('2dbfe11f-f1ed-4df1-8174-160f67ce925f'), primary_key=True, serialize=False),
        ),
    ]
